all:
	gcc hello_word.c -o hello

practice:
	gcc practice.c -o pract

practice2:
	gcc practice.c -o practice

clean:
	rm -f pract
	rm -f sky
	rm -f tok
sky:
	gcc sky.c -o sky
tok:
	gcc tokensSwitches.c -o tok
